spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
jms:
  event:
    topic:
      notification:
        create: create-event-notification
        update: update-event-notification
        delete: delete-event-notification
      request:
        create: create-event-request
        update: update-event-request
        delete: delete-event-request
