spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/product}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123qwe123QWE}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
